// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestTask.API.Data;

namespace TestTask.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211206091310_Creation")]
    partial class Creation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("TestTask.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<double>("Sum");

                    b.HasKey("Id");

                    b.ToTable("Orers");

                    b.HasData(
                        new { Id = 1, Name = "Order1", Sum = 50.0 },
                        new { Id = 2, Name = "Order2", Sum = 100.0 },
                        new { Id = 3, Name = "Order3", Sum = 200.0 }
                    );
                });

            modelBuilder.Entity("TestTask.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
